### ISSUE TITLE
Korrektur bei Quellencodierung

### ISSUE THREAD

**Issue by ELvetos** [HSR-Stud/NaT2#11]
Chapter -> Code-Länge, - Effizienz, -Redundanz

L (fix) ist ceil ( log2(n))

und nicht floor. -> Da so ja zuwenig Bits genommen werden.

**Comment by n04hk** [comment]
Ist in meinem Fork bereits korrigiert. Zusätzlich sind die Skript-Verweise aktualisiert und es gibt kleine Ergänzungen.

**Comment by ELvetos** [comment]
Super danke.

**Comment by n04hk** [comment]
Ist nun behoben (siehe Release 'FS2019')
